id: errors
namespace: dev

description: This flow will always fail. The `errors` branch tasks are executed on flow failure in parallel.

tasks:
- id: failed
  type: io.kestra.plugin.scripts.shell.Commands
  runner: PROCESS
  commands:
    - "exit 1"

errors:
  - id: parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: cleanup_task_1
        type: io.kestra.core.tasks.debugs.Return
        format: "running cleanup {{ task.id }}"

      - id: cleanup_task_2
        type: io.kestra.core.tasks.debugs.Return
        format: "running cleanup {{ task.id }}"

      - id: cleanup_task_3
        type: io.kestra.core.tasks.debugs.Return
        format: "running cleanup {{ task.id }}"
